"""empty message

Revision ID: 18e9d7748241
Revises: 471c26c89d4c
Create Date: 2022-05-30 20:10:52.908041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e9d7748241'
down_revision = '471c26c89d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('player1score', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('player2score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'player2score')
    op.drop_column('match', 'player1score')
    # ### end Alembic commands ###
