"""empty message

Revision ID: 471c26c89d4c
Revises: 47545c1a08a3
Create Date: 2022-05-29 17:38:55.237856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471c26c89d4c'
down_revision = '47545c1a08a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('player1choices', sa.String(length=64), nullable=True))
    op.add_column('match', sa.Column('player2choices', sa.String(length=64), nullable=True))
    op.add_column('match', sa.Column('player1messages', sa.String(length=64), nullable=True))
    op.add_column('match', sa.Column('player2messages', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'player2messages')
    op.drop_column('match', 'player1messages')
    op.drop_column('match', 'player2choices')
    op.drop_column('match', 'player1choices')
    # ### end Alembic commands ###
