./Solver legos all friend friend 500
./Solver legos all friend maxmin 500
./Solver legos all maxmin friend 500
./Solver legos all friend folk 500
./Solver legos all folk friend 500
./Solver legos all friend bully 500
./Solver legos all bully friend 500
./Solver legos all friend bouncer 500
./Solver legos all bouncer friend 500
./Solver legos all friend mbrl 500
./Solver legos all mbrl friend 500
./Solver legos all friend umbrl 500
./Solver legos all umbrl friend 500
./Solver legos all friend cfru 500
./Solver legos all cfru friend 500
./Solver legos all friend megaS++ 500
./Solver legos all megaS++ friend 500
./Solver legos all friend megaExp3 500
./Solver legos all megaExp3 friend 500

./Solver legos all maxmin maxmin 500
./Solver legos all maxmin folk 500
./Solver legos all folk maxmin 500
./Solver legos all maxmin bully 500
./Solver legos all bully maxmin 500
./Solver legos all maxmin bouncer 500
./Solver legos all bouncer maxmin 500
./Solver legos all maxmin mbrl 500
./Solver legos all mbrl maxmin 500
./Solver legos all maxmin umbrl 500
./Solver legos all umbrl maxmin 500
./Solver legos all maxmin cfru 500
./Solver legos all cfru maxmin 500
./Solver legos all maxmin megaS++ 500
./Solver legos all megaS++ maxmin 500
./Solver legos all maxmin megaExp3 500
./Solver legos all megaExp3 maxmin 500

./Solver legos all folk folk 500
./Solver legos all folk bully 500
./Solver legos all bully folk 500
./Solver legos all folk bouncer 500
./Solver legos all bouncer folk 500
./Solver legos all folk mbrl 500
./Solver legos all mbrl folk 500
./Solver legos all folk umbrl 500
./Solver legos all umbrl folk 500
./Solver legos all folk cfru 500
./Solver legos all cfru folk 500
./Solver legos all folk megaS++ 500
./Solver legos all megaS++ folk 500
./Solver legos all folk megaExp3 500
./Solver legos all megaExp3 folk 500

./Solver legos all bully bully 500
./Solver legos all bully bouncer 500
./Solver legos all bouncer bully 500
./Solver legos all bully mbrl 500
./Solver legos all mbrl bully 500
./Solver legos all bully umbrl 500
./Solver legos all umbrl bully 500
./Solver legos all bully cfru 500
./Solver legos all cfru bully 500
./Solver legos all bully megaS++ 500
./Solver legos all megaS++ bully 500
./Solver legos all bully megaExp3 500
./Solver legos all megaExp3 bully 500

./Solver legos all bouncer bouncer 500
./Solver legos all bouncer mbrl 500
./Solver legos all mbrl bouncer 500
./Solver legos all bouncer umbrl 500
./Solver legos all umbrl bouncer 500
./Solver legos all bouncer cfru 500
./Solver legos all cfru bouncer 500
./Solver legos all bouncer megaS++ 500
./Solver legos all megaS++ bouncer 500
./Solver legos all bouncer megaExp3 500
./Solver legos all megaExp3 bouncer 500

./Solver legos all mbrl mbrl 500
./Solver legos all mbrl umbrl 500
./Solver legos all umbrl mbrl 500
./Solver legos all mbrl cfru 500
./Solver legos all cfru mbrl 500
./Solver legos all mbrl megaS++ 500
./Solver legos all megaS++ mbrl 500
./Solver legos all mbrl megaExp3 500
./Solver legos all megaExp3 mbrl 500

./Solver legos all umbrl umbrl 500
./Solver legos all umbrl cfru 500
./Solver legos all cfru umbrl 500
./Solver legos all umbrl megaS++ 500
./Solver legos all megaS++ umbrl 500
./Solver legos all umbrl megaExp3 500
./Solver legos all megaExp3 umbrl 500

./Solver legos all cfru cfru 500
./Solver legos all cfru megaS++ 500
./Solver legos all megaS++ cfru 500
./Solver legos all cfru megaExp3 500
./Solver legos all megaExp3 cfru 500

./Solver legos all megaS++ megaS++ 500
./Solver legos all megaS++ megaExp3 500
./Solver legos all megaExp3 megaS++ 500

./Solver legos all megaExp3 megaExp3 500
